# Makefile to access the file in required mode and see whether we can access the file in required mode or not

build:
	gcc prog3.c -o myexe

run:
	./myexe ${ARGS} 

clean:
	rm myexe

help: 
	@echo 'Use as: "make build" / "make ARGS="filename mode" run" / "make clean" '
