# Makefile to run/execute the program in the given mode

build:
	gcc prog2.c -o myexe

run:
	./myexe ${ARGS}

clean:
	rm myexe

help: 
	@echo 'Use as "make build" / "make ARGS="filename mode" run " / "make clean" '


